config/routes.rb
FamilyLinux::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "family_data/tree"
  get "family_data/details"
  resources :family_start_points

  resources :family_documents

  resources :family_data

  resources :family_aliases

  resources :family_affinities

  

end

app/views/shared/_children_table.html.erb
    <table>
    <% odd_or_even = 0
       for child in children_table
         odd_or_even = 1 - odd_or_even 
    %>
         <tr valign="top" class="ListLine<%= odd_or_even %>">
                <%= render( :partial => "shared/family_datum_list_row", :object => child ) %>
         </tr>
       <% end %>
    </table>

app/views/shared/_family_affinities_list.html.erb
<table>
  <tr>
    <th>Name</th>
    <th> &nbsp; </th>
    <th> &nbsp; </th>
    <th> &nbsp; </th>
    <th>Relationship</th>
    <th>Connection name</th>
    <th> &nbsp; </th>
    <th> &nbsp; </th>
  </tr>

<% for family_affinity in family_affinities_list %>
  <tr>
<!-- Rev. 12/29/2013 to fix membid if -->
<%  if family_affinity.membid 
-%>
<!-- Rev. 12/19/2013 for RAILS 4 -->
<!--   was link_to family_affinity.name, { :controller => 'family_data', :action => 'show', :membid => family_affinity.membid } 
-->
      <td>

<%=      link_to family_affinity.name, method: :show, controller: :family_data, id: family_affinity.membid 
-%>
    </td>
    <td> &nbsp; </td>
    <td>[<%=h family_affinity.membid -%>]</td>
<%   else 
-%>
<!-- Rev. 12/19/2013 for RAILS 4 -->
<!--   was link_to family_affinity.name, { :controller => 'family_data', :action => 'show_list', :name => family_affinity.name } 
-->
       <td>
<%=      link_to family_affinity.name, method: :show_list, controller: :family_data, name: family_affinity.name 
-%>
    </td>
    <td> &nbsp; </td>
    <td> &nbsp; </td>
<%   end 
-%>
    <td> &nbsp; </td>
    <% if family_affinity.relationship == 'other' -%>
      <td><%=h family_affinity.other_type_value -%> of &nbsp &nbsp</td>
    <% else -%>
      <td><%=h family_affinity.relationship -%> of &nbsp &nbsp</td>
    <% end -%>
    <td>
<%           if family_affinity.connection_membid 
-%>
<!-- Rev. 12/19/2013 for RAILS 4; similar to above -->
<!-- was       link_to family_affinity.connection_name, { :controller => 'family_data', 
                   :action => 'show', :membid => family_affinity.connection_membid } 
-->
<%=            link_to family_affinity.connection_name, method: :show, controller: :family_data, 
                   membid: family_affinity.connection_membid 
-%>
<%         else 
-%>
<!-- was       link_to family_affinity.connection_name, { :controller => 'family_data', 
                   :action => 'show_list', :name => family_affinity.connection_name } 
-->
<%=            link_to family_affinity.connection_name, method: :show_list, controller: :family_data, 
                   membid: family_affinity.connection_name 
-%>
<%         end 
-%>
</td>
    <td> &nbsp; </td>
    <td>[<%=h family_affinity.connection_membid %>]</td>
    <td> &nbsp; </td>
    <% delete_msg = "Are you sure you want to delete relationship for " + 
        "'#{ family_affinity.connection_name }' as #{ family_affinity.relationship } of '#{ family_affinity.name }'?" %>
    <td>Relationship record <%= family_affinity.id %>: <%= link_to 'show, ', family_affinity %>
        <%= link_to 'edit, ', edit_family_affinity_path( family_affinity ) %> 
        <!-- was link_to 'destroy', family_affinity, :confirm => delete_msg, :method => :delete -->
        <!-- link_to 'Destroy', family_datum, data: { confirm: delete_msg }, :method => :delete -->
        <%= link_to 'destroy', family_affinity, data: { confirm: delete_msg }, :method => :delete  %></td>
  </tr>
  <% if family_affinity.comment && ( family_affinity.comment.length > 0 ) %>
    <tr><td colspan='5'>Comment: <%=h family_affinity.comment %></td></tr>
  <% end %>
<% end %>
</table>

app/views/shared/_family_affinity_new.html.erb
<!-- Rev. 12/22-29/2013 to adapt for RAILS 4 -->
<%= form_for( @family_affinity ) do | f | %>
  <!-- was f.error_messages -->
  <% if @family_affinity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize( @family_affinity.errors.count, "error") %> prohibited this family_affinity from being saved:</h2>

      <ul>
      <% @family_affinity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :membid %><br />
    <%= f.text_field :membid %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br />
    <%= f.select :relationship, %w{ spouse cousin friend step_sibling godfather godmother other }, 
      :include_blank => true, :size => 3 %>
  </div>
  <div class="field">
    <%= f.label :other_type_value %><br />
    <%= f.text_field :other_type_value %>
  </div>
  <div class="field">
    <%= f.label :connection_name %><br />
    <%= f.text_field :connection_name %>
  </div>
  <div class="field">
    <%= f.label :connection_membid %><br />
    <%= f.text_field :connection_membid %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
<!-- Rev. 12/22/2013 to correct 'submit' label -->
<!-- f.submit ( controller.action_name == 'new' ? 'Create' : "Update \"#{ :name }\"" ) -->
    <%= f.submit %>
  </div>
<% end %>

app/views/shared/_family_alias_new.html.erb
  <p>
    Record name: <%= family_alias_new.label :name %> <%= family_alias_new.text_field :name, 
        :value => @name, :size => 33 %> [link: <%= family_alias_new.text_field :membid, 
        :value => @membid, :size => 1 %>]
    Type of name: <%= family_alias_new.select :type_of_name, %w{      
      birth_name nickname maiden_name married_name professional_name aka other }, 
      :include_blank => true, :size => 3 %>
      (Other type of name: <%= family_alias_new.text_field :other_type_value, :size => '2' %>)
  </p>
  <p>
    Alternate name: <%= family_alias_new.text_field :alias_name %>
  </p>
  <p>
    <%= family_alias_new.label :comment %><br />
    <%= family_alias_new.text_area :comment %>
  </p>

app/views/shared/_family_aliases_list.html.erb
<!-- Rev. 08/21/2012 to debug -->
<!-- Rev. 09/04/2012 to improve formatting and to debug -->
<!-- Rev. 11/11/2012 to improve formatting -->
<!-- Rev. 12/18/2013 to update link_to with RAILS 4 -->
<% odd_or_even = 0 
-%>
<% prev_name = '' 
   prev_membid = 0 
-%>
<table>
<% for family_alias in family_aliases_list
     odd_or_even = 1 - odd_or_even 
-%>
     <tr valign="top" class="ListLine<%= odd_or_even -%>">
       <td>
<%       unless controller.controller_name == 'family_data' 
           unless ( family_alias.name == prev_name ) && ( family_alias.membid == prev_membid )
             if family_alias.membid 
-%>
<!-- Rev. link_to to update 12/18/2013 -->
<%=            link_to family_alias.name, method: :show, controller: :family_data, id: family_alias.membid 
%>
<%=                '[' + h( family_alias.membid ) + ']'
-%>
<%           else 
-%>
<!-- Rev. link_to to update 12/18/2013 -->
<%=            link_to family_alias.name, method: :show, controller: :family_data, :name => family_alias.name
-%>
<%           end
           end 
           prev_name = family_alias.name
           prev_membid = family_alias.membid
-%>        &nbsp;
<%       end
-%>
         </td><td>
<%       if family_alias.type_of_name 
           this_tag = ( family_alias.type_of_name.downcase == "other" ?
               family_alias.other_type_value : family_alias.type_of_name )
         else
           this_tag = "relationship"
         end
-%>
<%=      link_to this_tag + ': ' + family_alias.alias_name, edit_family_alias_path(family_alias)
-%>      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
       </td><td><small>
<%=h   family_alias.alias_hash5 
-%>    &nbsp; &nbsp; 
       Record ID: <%=h family_alias.id %> &nbsp; &nbsp; 
       <br />
       Updated: <%=h family_alias.updated_at %> &nbsp; &nbsp; 
       Created: <%=h family_alias.created_at %></small>
     </td></tr>
<%   if family_alias.comment && ( family_alias.comment.length > 0 ) 
       odd_or_even = 1 - odd_or_even 
-%>    <tr valign='top' class="ListLine<%= odd_or_even %>"><td colspan='3'><%=h family_alias.comment %>
       </td></tr>
<%   end
   end
-%>
</table>

app/views/shared/_family_data_list.html.erb
<!-- _family_data_list.html.erb
Rev. 12/17/2013 to use data: { confirm: 'Text' } in destroy statement, per RAILS 4.0 warning
-->
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th>Gender</th>
    <th>Birth date and place</th>
    <th>Parents</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th>Record Id</th>
    <th>Updated/Created</th>
  </tr>

<% for family_datum in @family_data %>
  <tr>
    <td><%= link_to family_datum.name, family_datum %></td>
    <td>[<%=h family_datum.membid %>]</td>
    <td><%=h family_datum.gender %></td>
    <td><%=h family_datum.birth_date %><br />
        <%=h family_datum.birth_place %></td>
    <td><%=h family_datum.father %><br />
        <%=h family_datum.mother %></td>
    <td>[<%=h family_datum.fatherid %>]<br />
        [<%=h family_datum.motherid %>]</td>
    <td> &nbsp; </td>
    <% delete_msg = "Are you sure you want to delete record #{ family_datum.id } for #{ family_datum.name }?" %>
    <td> &nbsp; 
        <%= link_to 'Edit', edit_family_datum_path(family_datum) %><br />
        <%= link_to 'Destroy', family_datum, data: { confirm: delete_msg }, :method => :delete %></td>
    <td> &nbsp; </td>
    <td><small><%=h family_datum.id %><br /><%=h family_datum.hash5 %></small></td>
    <td><small><%=h family_datum.updated_at %><br />
        <%=h family_datum.created_at %></small></td>
  </tr>
<% end %>
</table>

app/views/shared/_family_data_show.html.erb
<!-- Rev. 09/26/2012 to create partial to share btn family_data and family_views -->
<a href='#alternate_names'>Alternate names</a> | 
<a href='#affinities'>Other relationships</a> | 
<a href='#documents'>Events and documents</a> | 
<a href='#hash5_results'>Records with same 5-char. hash</a>
<a name='top'></a>
<% if @family_datum.name
     odd_or_even = 0 %>
     <hr />
     <table>
       <tr valign="top" class="ListLine<%= odd_or_even %>">
         <td>Name: </td>
         <%= render( :partial => "shared/family_datum_list_row", :object => @family_datum ) %>
       </tr>
<!-- Father -->
     <% if @fathers.length > 0 %>
          <tr><td colspan='10'><hr /></td></tr>
          <% odd_or_even = 1
          for parent in @fathers
            if parent.gender == 'm'
          %>
              <tr valign='top' class='ListLine<%= odd_or_even %>'>
                <td>father: </td>
                <%= render( :partial => 'shared/family_datum_list_row', :object => parent ) %>
              </tr>
            <% end %>
          <% end %>
     <% elsif @family_datum.father %>
          <tr>
            <td> </td>
            <td colspan='2'>
            </td>
            <td colspan='4'>No entry for <b>&quot<%=h @family_datum.father %>&quot</b>
                 as <b>parent</b> of <b><%=h @family_datum.name %></b> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
                 <%= link_to 'New entry', new_family_datum_path %> 
            </td>
          </tr>
     <% else %>
          <tr>
            <td> </td>
            <td colspan='2'>  </td>
            <td>No entry for father of <b><%=h @family_datum.name %>
                    </b> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
                    <%= link_to 'New entry', new_family_datum_path %> 
            </td>
          </tr>
     <% end %>
<!-- Mother -->
     <% if @mothers.length > 0 %>
          <tr><td colspan='10'><hr /></td></tr>
          <% odd_or_even = 1
          for parent in @mothers
            if parent.gender == 'f'
          %>
              <tr valign='top' class='ListLine<%= odd_or_even %>'>
                <td>mother: </td>
                <%= render( :partial => 'shared/family_datum_list_row', :object => parent ) %>
              </tr>
            <% end %>
          <% end %>
     <% elsif @family_datum.mother %>
          <tr>
            <td> </td>
            <td colspan='2'>
            </td>
            <td colspan='4'>No entry for <b>&quot<%=h @family_datum.mother %>&quot</b>
                 as <b>parent</b> of <b><%=h @family_datum.name %></b> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
                 <%= link_to 'New entry', new_family_datum_path %> 
            </td>
          </tr>
     <% else %>
          <tr>
            <td> </td>
            <td colspan='2'>  </td>
            <td>No entry for mother of <b><%=h @family_datum.name %>
                    </b> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
                    <%= link_to 'New entry', new_family_datum_path %> 
            </td>
          </tr>
         <% render(:partial => 'shared/show_parents', :object => @mothers,
              :locals => { :gender_needed => 'f', :child_rcd => @family_datum,
              :parent_name => @family_datum.mother }) %>
      <% end %>
      </table>
<% else %>
  <%= link_to 'New entry', new_family_datum_path %></p>
<% end %>
<hr />
<!-- Alternate names -->
  <% form_tag( { :controller => 'family_aliases', :action => 'new' } ) do -%>
         <%= hidden_field_tag( :membid, @family_datum.membid, :value => @family_datum.membid ) -%>
         <%= hidden_field_tag( :name, @family_datum.name, :value => @family_datum.name ) -%>
         <%= submit_tag "New alternate name record for #{ @family_datum.name }" %>
  <% end %>
<% if @family_aliases && @family_aliases.length > 0 %>
     <h3>Alternate names (count <%=h @family_aliases.length.to_s %>) &nbsp;  &nbsp;  &nbsp;  &nbsp; <a name='alternate_names'></a><a href='#top'>Back to top</a></h3>
     <%= render( :partial => "shared/family_aliases_list", :object => @family_aliases ) %>
<% else %>
  No alternate names found for <%=h @family_datum.name %>
<% end %>
<hr />
<!-- Children -->
  <% form_tag( { :controller => 'family_data', :action => 'new' } ) do -%>
    <% if @family_datum.gender == "m" %>
      <%= hidden_field_tag( :fatherid, @family_datum.membid, 
          :value => @family_datum.membid ) -%>
      <%= hidden_field_tag( :father, @family_datum.name, :value => @family_datum.name ) -%>
    <% elsif @family_datum.gender == "f" %>
      <%= hidden_field_tag( :motherid, @family_datum.membid, 
          :value => @family_datum.membid ) -%>
      <%= hidden_field_tag( :mother, @family_datum.name, :value => @family_datum.name ) -%>
    <% end %>
    <%= submit_tag "New child record" %>
  <% end %>
<% if @children.length > 0 %>
  <h3>Children of <%= @family_datum.name %> (count of <%= @children.length -%>)</h3>
    <%= render( :partial => "shared/children_table", :object => @children ) %>
<% else %>
  No child records found for <%= @family_datum.name %>
<% end %>
<hr />

<!-- Documents -->
<h3>Documents and events &nbsp;  &nbsp;  &nbsp;  &nbsp;  
  <%= link_to 'New entry for document or event', new_family_document_path %> &nbsp; 
  <a name='documents'></a><a href='#top'>Back to top</a></h3>
<% if @family_documents.length > 0 %>
  <p />Documents and events for <b><%= @family_datum.name %></b>: (count of <%= @family_documents.length -%>)
    <%= render( :partial => "shared/family_documents_list", :object => @family_documents  ) %>
<% else %>
    <p>No entry for documents and events for <b><%=h @family_datum.name %></b> </p>
<% end %>
<hr />

<!-- Affinities -->
<h3>Other relationships &nbsp;  &nbsp;  &nbsp;  &nbsp; 
    <%= link_to 'New relationship entry', new_family_affinity_path %> &nbsp; 
   <a name='affinities'></a><a href='#top'>Back to top</a></h3>
<% if @family_affinities.length > 0 %>
  <p>Other relationships for <b><%= @family_datum.name %></b>: (count of <%= @family_affinities.length -%>)
<%= render( :partial => "shared/family_affinities_list", :object => @family_affinities  ) %>
</p>
<% elsif @possible_affinities.length == 0 %>
    <p>No other relationships listed for <b><%=h @family_datum.name %></b> </p>
<% else %>
  <p>Possible additional records for relationships: (count of <%= @possible_affinities.length -%>)</p>
<%= render( :partial => "shared/family_affinities_list", :object => @possible_affinities  ) %>
<% end %></p>
<hr />

<p>Record ID: <%=h @family_datum.id %> &nbsp; &nbsp; hash5: <%=h @family_datum.hash5 %> &nbsp; &nbsp; 
Updated: <%=h @family_datum.updated_at %> &nbsp; &nbsp; Created: <%=h @family_datum.created_at %></p>
<% unless controller.controller_name == 'family_view' %>
  <%= link_to 'Edit this record', edit_family_datum_path(@family_datum) %> |
<% end %>
<%= link_to 'List all person records', family_data_path %>

app/views/shared/_family_datum_list_row.html.erb
<!-- partial _family_data_list_row -->
<!-- Rev. 08/19/2012 to reformat -->
<!-- Rev. 08/27/2012 to make parent names links, when possible -->
<!-- Rev. 09/20/2012 for formatting -->
<!-- Rev. 09/23-28/2012 to implement override_date -->
<!-- Rev. 12/17/2013 to elim. some debugging statements and reformat destroy for RAILS 4 -->
<td><%= link_to family_datum_list_row.name, family_datum_list_row %></td>
<% display_date = ( family_datum_list_row.birth_date.nil? ?  
   h( family_datum_list_row.override_year.nil? ? '' : family_datum_list_row.override_year ) : 
   h( fmt_date_format_to_string( family_datum_list_row.birth_date ) ) )
-%>
<td><%=h display_date %><br />
    <%=h family_datum_list_row.birth_place %></td>
<td>[<%=h family_datum_list_row.membid %>]</td>

<td><%=h family_datum_list_row.father %><br />
    <%=h family_datum_list_row.mother %></td>
<td>[<%=h family_datum_list_row.fatherid %>]<br />
    [<%=h family_datum_list_row.motherid %>]</td>
<td> &nbsp; </td>
<% delete_msg = "Are you sure you want to delete record #{ family_datum_list_row.id } for #{ family_datum_list_row.name }?" %>
<td> 
<%= link_to 'Tree', { :controller => 'family_data', 
        :action => 'tree', :id => family_datum_list_row.membid }  
-%>
        <%= link_to 'Edit', edit_family_datum_path(family_datum_list_row) %> 
        <%= link_to 'Destroy', family_datum_list_row, data: { confirm: delete_msg }, :method => :delete %></td>
    <td> &nbsp; </td>
    <td><small><%=h family_datum_list_row.gender %>., <%=h family_datum_list_row.id %><br /><%=h family_datum_list_row.hash5 %></small></td>
    <td><small><%=h family_datum_list_row.updated_at %><br />
        <%=h family_datum_list_row.created_at %></small></td>

app/views/shared/_family_documents_list.html.erb
<% prev_membid = 0 -%>
<table>
  <tr>
    <% unless controller.controller_name == 'family_data' %>
      <th>Name</th>
    <% end %>
    <th>Event type and date</th>
    <th>Event place</th>
    <th>Doc descrip</th>
    <th>Doc type</th>
    <th>Doc link</th>
    <th>Comment</th>
  </tr>

<% for family_document in @family_documents %>
  <tr>
    <% unless controller.controller_name == 'family_data' %>
      <td><b>
        <% unless family_document.membid == prev_membid
             if family_document.membid 
        -%>
               <%= link_to family_document.name, { :controller => 'family_data', 
                  :action => 'show', :membid => family_document.membid } 
               -%>
          <% else 
          -%>
               <%= link_to family_document.name, { :controller => 'family_data', 
                   :action => 'show', :name => family_document.name } %>
          <% end %>
        <% end 
        prev_membid = family_document.membid %>
        </b>[<% family_document.membid -%>]
      </td>
    <% end %>
    <td><%=h family_document.event_type %>: <%=h family_document.event_date %></td>
    <td><%=h family_document.event_place %> (Place type: <%=h family_document.place_type %>)</td>
    <td><%=h family_document.doc_descrip %></td>
    <td><%=h family_document.doc_type %></td>
    <td><%=h family_document.doc_link %></td>
    <td><%=h family_document.comment %></td>
    <% delete_msg = "Are you sure you want to delete #{ family_document.doc_descrip } " + 
        "for '#{ family_document.name }'?" %>
    <td><%= link_to 'Show', family_document %> &nbsp; 
        <%= link_to 'Edit', edit_family_document_path(family_document) %><br />
    <%= link_to 'Destroy entry', family_document, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/shared/_layout_side_menu.html.erb
<!-- _layout_side_menu written 06/12/2012 ADRoth -->
<!-- Rev. 12/09-23/2013 for family_bkgd project -->
<p style="color: gray"><%= flash[:notice] %></p>
  <div id="banner"> <%= controller.action_name.camelcase %> ||  <%= controller.controller_name.camelcase %>
  </div>
  <div id="columns">
     <div id="side">
       <% if ENV["RAILS_ENV"] == 'development' %>
            Controller: <b><%= controller.controller_name%></b><br /><hr />
       <% end %>
       <% unless ENV["RAILS_ENV"] == 'production' %>
            Environment: <b><%=h ENV["RAILS_ENV"] %></b><br /><hr />
       <% end %>
       <a href="http://localhost:3000/index.html">Home</a><br />
       <% unless [ 'welcome', 'view_only' ].include?( controller.controller_name ) %>
            <a href="http://localhost:3000/family_start_points">Start points</a><br />
            <a href="http://localhost:3000/family_aliases">All alternate names</a><br />
            <a href="http://localhost:3000/family_documents">All documents and events</a><br />
            <a href="http://localhost:3000/family_data">All individuals</a><br />
            <a href="http://localhost:3000/family_affinities">All relationship records</a><br />
       <% end %>
               ___________
               <!-- ul -->
<!--               %w{ index }.each do |action|  -->
                <!-- controller.methods.each do | action | -%  -->
                       <!-- li -->
                       <!-- link_to_unless_current(action.capitalize, :action => action) -->
                       <!-- /li -->
                   <!-- end -->
               <!-- /ul -->
           </div>
       </div>

app/views/shared/_nav_line.html.erb
<!-- <%= controller.controller_name %> -->
<!-- _nav_line written 06/27/2012 A.D. Roth for pagination in method passed as nav_line-->
<!-- uses @offset, @max_rows, and @table_count -->
<!-- must be run under same controller for the links-->
<% if @max_rows < @table_count %>
  <% end_point = [ @offset + @max_rows, @table_count ].min %>
  <% prev_start = [ @offset + 1 - @max_rows, 1 ].max %>
<p class="Navigation">From <%=h @offset + 1 %> to <%=h end_point %> of <%=h @table_count %>  &nbsp; &nbsp; 
   <% if @offset > @max_rows / 2 %>
     <%= link_to '|<< To First (1)', { 
      :controller => controller.controller_name, 
      :action => nav_line, 
      :curr_offset => @offset,
      :next_offset => 'First' 
     } %> &nbsp; &nbsp; 
     <%= link_to "<< Prev Page (#{ prev_start }-#{ @offset })", { 
      :controller => controller.controller_name, 
      :action => nav_line, 
      :curr_offset => @offset,
      :next_offset => 'Prev' 
     } %> &nbsp; &nbsp;
   <% end %>
   <% unless @table_count - @offset < @max_rows / 2 %>
     <%= link_to "Next Page ( #{ [ end_point + 1, @table_count ].min }-#{ [ end_point + @max_rows, @table_count ].min }) >>", { 
      :controller => controller.controller_name, 
      :action => nav_line, 
      :curr_offset => @offset,
      :next_offset => 'Next' 
     } %> &nbsp; &nbsp; 
     <%= link_to "Last (#{ @table_count }) >>|", { 
      :controller => controller.controller_name, 
      :action => nav_line, 
      :curr_offset => @offset,
      :next_offset => 'Last' 
     } %>
   <% end %>
</p>
<% end %>

app/views/shared/_show_parents.html.erb
<tr>   <td><%= link_to show_parents[0].name, show_parents[0] %></td></tr>
<% odd_or_even = 1
   if show_parents.length > 0
     for parent in show_parents
       if parent.gender == gender_needed
%>
        <tr valign='top' class='ListLine<%= odd_or_even %>'>
           <td>parent: 
           </td>
           <%= render( :partial => 'shared/family_datum_list_row', :object => parent ) %>
         </tr>
    <% end %>
  <% end %>
<% elsif parent_name %>
     <tr>
       <td> </td>
       <td colspan='2'>
       </td>
       <td colspan='4'>No entry for <b>&quot<%=h parent_name %>&quot</b>
               as <b>parent</b> of <b><%=h child_rcd.name %></b> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
               <%= link_to 'New entry', new_family_datum_path %> 
       </td>
     </tr>
<% else %>
     <tr>
       <td> </td>
       <td colspan='2'>
       </td>
       <td>No entry for parent of <b><%=h child_rcd.name %>
               </b> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
               <%= link_to 'New entry', new_family_datum_path %> 
       </td>
     </tr>
<% end %>