config/routes.rb
FamilyLinux::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "family_data/tree"
  get "family_data/details"
  resources :family_start_points

  resources :family_documents

  resources :family_data

  resources :family_aliases

  resources :family_affinities

  

end

app/models/family_document.rb
class FamilyDocument < ActiveRecord::Base
  #-- Rev. 12/08/2013 to add has_many
  belongs_to :family_data
end

app/controllers/family_documents_controller.rb
class FamilyDocumentsController < ApplicationController
  # GET /family_documents
  # GET /family_documents.xml
  # ---------------------------------------------
  # index
  # Rev. 06/27/2012 to tweak @offset calculation and create method prep_nav_values
  # ---------------------------------------------
  def index
    require 'general_helpers_201207'
    @table_count = FamilyDocument.count
    prep_nav_values( params )
    @family_documents = FamilyDocument.find( :all, :offset => @offset, :limit => @max_rows )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @family_documents }
    end
  end

  # GET /family_documents/1
  # GET /family_documents/1.xml
  def show
    @family_document = FamilyDocument.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @family_document }
    end
  end

  # GET /family_documents/new
  # GET /family_documents/new.xml
  def new
    @family_document = FamilyDocument.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @family_document }
    end
  end

  # GET /family_documents/1/edit
  def edit
    @family_document = FamilyDocument.find(params[:id])
  end

  # POST /family_documents
  # POST /family_documents.xml
  def create
    @family_document = FamilyDocument.new(params[:family_document])

    respond_to do |format|
      if @family_document.save
        flash[:notice] = 'FamilyDocument was successfully created.'
        #  format.html { redirect_to(@family_document) }
        format.html { redirect_to(url_for( :controller => 'family_data', 
              :action => 'tree', :id => @family_document[ :membid ] ) ) }

        format.xml  { render :xml => @family_document, :status => :created, :location => @family_document }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @family_document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /family_documents/1
  # PUT /family_documents/1.xml
  def update
    @family_document = FamilyDocument.find(params[:id])

    respond_to do |format|
      if @family_document.update_attributes(params[:family_document])
        flash[:notice] = 'FamilyDocument was successfully updated.'
        format.html { redirect_to(@family_document) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @family_document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /family_documents/1
  # DELETE /family_documents/1.xml
  def destroy
    @family_document = FamilyDocument.find(params[:id])
    @family_document.destroy

    respond_to do |format|
      format.html { redirect_to(family_documents_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/originals/family_documents_controller.rb
class FamilyDocumentsController < ApplicationController
  before_action :set_family_document, only: [:show, :edit, :update, :destroy]

  # GET /family_documents
  # GET /family_documents.json
  def index
    @family_documents = FamilyDocument.all
  end

  # GET /family_documents/1
  # GET /family_documents/1.json
  def show
  end

  # GET /family_documents/new
  def new
    @family_document = FamilyDocument.new
  end

  # GET /family_documents/1/edit
  def edit
  end

  # POST /family_documents
  # POST /family_documents.json
  def create
    @family_document = FamilyDocument.new(family_document_params)

    respond_to do |format|
      if @family_document.save
        format.html { redirect_to @family_document, notice: 'Family document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @family_document }
      else
        format.html { render action: 'new' }
        format.json { render json: @family_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /family_documents/1
  # PATCH/PUT /family_documents/1.json
  def update
    respond_to do |format|
      if @family_document.update(family_document_params)
        format.html { redirect_to @family_document, notice: 'Family document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @family_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /family_documents/1
  # DELETE /family_documents/1.json
  def destroy
    @family_document.destroy
    respond_to do |format|
      format.html { redirect_to family_documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_document
      @family_document = FamilyDocument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_document_params
      params.require(:family_document).permit(:doc_descrip, :doc_type, :doc_link, :name, :membid, :comment, :created_at, :updated_at, :event_type, :event_date, :event_place, :place_type, :other_doc_type, :other_place_type, :other_event_type)
    end
end

app/helpers/family_documents_helper.rb
module FamilyDocumentsHelper
end

app/views/original_views/family_documents/_form.html.erb
<%= form_for(@family_document) do |f| %>
  <% if @family_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family_document.errors.count, "error") %> prohibited this family_document from being saved:</h2>

      <ul>
      <% @family_document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :doc_descrip %><br>
    <%= f.text_field :doc_descrip %>
  </div>
  <div class="field">
    <%= f.label :doc_type %><br>
    <%= f.text_field :doc_type %>
  </div>
  <div class="field">
    <%= f.label :doc_link %><br>
    <%= f.text_field :doc_link %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :membid %><br>
    <%= f.number_field :membid %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :event_place %><br>
    <%= f.text_field :event_place %>
  </div>
  <div class="field">
    <%= f.label :place_type %><br>
    <%= f.text_field :place_type %>
  </div>
  <div class="field">
    <%= f.label :other_doc_type %><br>
    <%= f.text_field :other_doc_type %>
  </div>
  <div class="field">
    <%= f.label :other_place_type %><br>
    <%= f.text_field :other_place_type %>
  </div>
  <div class="field">
    <%= f.label :other_event_type %><br>
    <%= f.text_field :other_event_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/original_views/family_documents/edit.html.erb
<h1>Editing family_document</h1>

<%= render 'form' %>

<%= link_to 'Show', @family_document %> |
<%= link_to 'Back', family_documents_path %>

app/views/original_views/family_documents/index.html.erb
<h1>Listing family_documents</h1>

<table>
  <thead>
    <tr>
      <th>Doc descrip</th>
      <th>Doc type</th>
      <th>Doc link</th>
      <th>Name</th>
      <th>Membid</th>
      <th>Comment</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Event type</th>
      <th>Event date</th>
      <th>Event place</th>
      <th>Place type</th>
      <th>Other doc type</th>
      <th>Other place type</th>
      <th>Other event type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @family_documents.each do |family_document| %>
      <tr>
        <td><%= family_document.doc_descrip %></td>
        <td><%= family_document.doc_type %></td>
        <td><%= family_document.doc_link %></td>
        <td><%= family_document.name %></td>
        <td><%= family_document.membid %></td>
        <td><%= family_document.comment %></td>
        <td><%= family_document.created_at %></td>
        <td><%= family_document.updated_at %></td>
        <td><%= family_document.event_type %></td>
        <td><%= family_document.event_date %></td>
        <td><%= family_document.event_place %></td>
        <td><%= family_document.place_type %></td>
        <td><%= family_document.other_doc_type %></td>
        <td><%= family_document.other_place_type %></td>
        <td><%= family_document.other_event_type %></td>
        <td><%= link_to 'Show', family_document %></td>
        <td><%= link_to 'Edit', edit_family_document_path(family_document) %></td>
        <td><%= link_to 'Destroy', family_document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family document', new_family_document_path %>

app/views/original_views/family_documents/new.html.erb
<h1>New family_document</h1>

<%= render 'form' %>

<%= link_to 'Back', family_documents_path %>

app/views/original_views/family_documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doc descrip:</strong>
  <%= @family_document.doc_descrip %>
</p>

<p>
  <strong>Doc type:</strong>
  <%= @family_document.doc_type %>
</p>

<p>
  <strong>Doc link:</strong>
  <%= @family_document.doc_link %>
</p>

<p>
  <strong>Name:</strong>
  <%= @family_document.name %>
</p>

<p>
  <strong>Membid:</strong>
  <%= @family_document.membid %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @family_document.comment %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @family_document.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @family_document.updated_at %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @family_document.event_type %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @family_document.event_date %>
</p>

<p>
  <strong>Event place:</strong>
  <%= @family_document.event_place %>
</p>

<p>
  <strong>Place type:</strong>
  <%= @family_document.place_type %>
</p>

<p>
  <strong>Other doc type:</strong>
  <%= @family_document.other_doc_type %>
</p>

<p>
  <strong>Other place type:</strong>
  <%= @family_document.other_place_type %>
</p>

<p>
  <strong>Other event type:</strong>
  <%= @family_document.other_event_type %>
</p>

<%= link_to 'Edit', edit_family_document_path(@family_document) %> |
<%= link_to 'Back', family_documents_path %>