config/routes.rb
FamilyLinux::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "family_data/tree"
  get "family_data/details"
  resources :family_start_points

  resources :family_documents

  resources :family_data

  resources :family_aliases

  resources :family_affinities

  

end

app/models/family_affinity.rb
class FamilyAffinity < ActiveRecord::Base
  #-- Rev. 12/08/2013 to add has_many
  belongs_to :family_data
end

app/controllers/family_affinities_controller.rb
# ++-------------------------------
# class FamilyAffinitiesController
# 
# Rev. 12/18-19/2013 for RAILS 4
# ++-------------------------------
class FamilyAffinitiesController < ApplicationController
  before_action :set_family_affinity, only: [:show, :edit, :update, :destroy]
  include ApplicationHelper

  # ++---------------------------------------------
  # index
  #
  # Rev. 06/27/2012 to tweak @offset calculation and create method prep_nav_values
  # Rev. 12/18-19/2013 for RAILS 4
  # ++---------------------------------------------
  # GET /family_affinities
  # GET /family_affinities.xml
  def index
    @table_count = FamilyAffinity.count
    prep_nav_values( params )
    #  @family_affinities = FamilyAffinity.find( :all, :order => 'name, relationship, connection_name', 
    #      :offset => @offset, :limit => @max_rows )
    @family_affinities = FamilyAffinity.limit( @max_rows ).offset( @offset ).order( :name, :relationship, 
        :connection_name ) 
      
    #  respond_to do |format|
    #    format.html # index.html.erb
    #    format.xml  { render :xml => @family_affinities }
    #  end
  end  #  index

  # ++---------------------------------------------
  # show
  #
  # Rev. 12/19/2013 for RAILS 4
  # ++---------------------------------------------
  # GET /family_affinities/1
  # GET /family_affinities/1.xml
  def show
    #  @family_affinity = FamilyAffinity.find(params[:id])

    #  respond_to do |format|
    #    format.html # show.html.erb
    #    format.xml  { render :xml => @family_affinity }
    #  end
  end  #  show

  # ++---------------------------------------------
  # new
  #
  # Rev. 12/19/2013 for RAILS 4
  # ++---------------------------------------------
  # GET /family_affinities/new
  # GET /family_affinities/new.xml
  def new
    @family_affinity = FamilyAffinity.new
puts 'Debug: defining another @family_affinity'
    #  respond_to do |format|
    #    format.html # new.html.erb
    #    format.xml  { render :xml => @family_affinity }
    #  end
  end  #  new

  # ++---------------------------------------------
  # edit
  #
  # Rev. 12/19/2013 for RAILS 4
  # ++---------------------------------------------
  # GET /family_affinities/1/edit
  def edit
    #  @family_affinity = FamilyAffinity.find(params[:id])
  end

  # ++---------------------------------------------
  # create
  #
  # Rev. 12/19/2013 for RAILS 4
  # ++---------------------------------------------
  # POST /family_affinities
  # POST /family_affinities.xml
  def create
    #  @family_affinity = FamilyAffinity.new(params[:family_affinity])
    @family_affinity = FamilyAffinity.new( family_affinity_params )

    respond_to do |format|
      if @family_affinity.save
        #  flash[:notice] = 'FamilyAffinity was successfully created.'
        #  format.html { redirect_to(@family_affinity) }
        #  format.xml  { render :xml => @family_affinity, :status => :created, :location => @family_affinity }
        format.html { redirect_to @family_affinity, notice: 'Family affinity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @family_affinity }
      else
        #  format.html { render :action => "new" }
        #  format.xml  { render :xml => @family_affinity.errors, :status => :unprocessable_entity }
        format.html { render action: 'new' }
        format.json { render json: @family_affinity.errors, status: :unprocessable_entity }
      end
    end

  end  #  create  

  # ++---------------------------------------------
  # update
  #
  # Rev. 12/19/2013 for RAILS 4
  # ++---------------------------------------------
  # PUT /family_affinities/1
  # PUT /family_affinities/1.xml
  def update
    #  @family_affinity = FamilyAffinity.find(params[:id])

    #  end
    respond_to do |format|
      #  if @family_affinity.update_attributes(params[:family_affinity])
      if @family_affinity.update( family_affinity_params )
        #  flash[:notice] = 'FamilyAffinity was successfully updated.'
        #  format.html { redirect_to(@family_affinity) }
        #  format.xml  { head :ok }
        format.html { redirect_to @family_affinity, notice: 'Family affinity was successfully updated.' }
        format.json { head :no_content }
      else
        #  format.html { render :action => "edit" }
        #  format.xml  { render :xml => @family_affinity.errors, :status => :unprocessable_entity }
        format.html { render action: 'edit' }
        format.json { render json: @family_affinity.errors, status: :unprocessable_entity }
      end
    end
  end  #  update

  # ++---------------------------------------------
  # destroy
  #
  # Rev. 12/19/2013 for RAILS 4
  # ++---------------------------------------------
  # DELETE /family_affinities/1
  # DELETE /family_affinities/1.xml
  def destroy
    #  @family_affinity = FamilyAffinity.find(params[:id])
    @family_affinity.destroy

    respond_to do |format|
      #  format.html { redirect_to( family_affinities_url ) }
      #  format.xml  { head :ok }
      format.html { redirect_to family_affinities_url }
      format.json { head :no_content }
    end
  end  #  destroy

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_affinity
      @family_affinity = FamilyAffinity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_affinity_params
      params.require(:family_affinity).permit( :name, :membid, :relationship, :other_type_value, 
          :connection_name, :connection_membid, :comment, :created_at, :updated_at)
    end
end  #  FamilyAffinitiesController

app/controllers/originals/family_affinities_controller.rb
class FamilyAffinitiesController < ApplicationController
  before_action :set_family_affinity, only: [:show, :edit, :update, :destroy]

  # GET /family_affinities
  # GET /family_affinities.json
  def index
    @family_affinities = FamilyAffinity.all
  end

  # GET /family_affinities/1
  # GET /family_affinities/1.json
  def show
  end

  # GET /family_affinities/new
  def new
    @family_affinity = FamilyAffinity.new
  end

  # GET /family_affinities/1/edit
  def edit
  end

  # POST /family_affinities
  # POST /family_affinities.json
  def create
    @family_affinity = FamilyAffinity.new(family_affinity_params)

    respond_to do |format|
      if @family_affinity.save
        format.html { redirect_to @family_affinity, notice: 'Family affinity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @family_affinity }
      else
        format.html { render action: 'new' }
        format.json { render json: @family_affinity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /family_affinities/1
  # PATCH/PUT /family_affinities/1.json
  def update
    respond_to do |format|
      if @family_affinity.update(family_affinity_params)
        format.html { redirect_to @family_affinity, notice: 'Family affinity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @family_affinity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /family_affinities/1
  # DELETE /family_affinities/1.json
  def destroy
    @family_affinity.destroy
    respond_to do |format|
      format.html { redirect_to family_affinities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_affinity
      @family_affinity = FamilyAffinity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_affinity_params
      params.require(:family_affinity).permit(:name, :membid, :relationship, :other_type_value, :connection_name, :connection_membid, :comment, :created_at, :updated_at)
    end
end

app/helpers/family_affinities_helper.rb
module FamilyAffinitiesHelper
end

app/views/original_views/family_affinities/_form.html.erb
<%= form_for(@family_affinity) do |f| %>
  <% if @family_affinity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family_affinity.errors.count, "error") %> prohibited this family_affinity from being saved:</h2>

      <ul>
      <% @family_affinity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :membid %><br>
    <%= f.number_field :membid %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br>
    <%= f.text_field :relationship %>
  </div>
  <div class="field">
    <%= f.label :other_type_value %><br>
    <%= f.text_field :other_type_value %>
  </div>
  <div class="field">
    <%= f.label :connection_name %><br>
    <%= f.text_field :connection_name %>
  </div>
  <div class="field">
    <%= f.label :connection_membid %><br>
    <%= f.number_field :connection_membid %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/original_views/family_affinities/edit.html.erb
<h1>Editing family_affinity</h1>

<%= render 'form' %>

<%= link_to 'Show', @family_affinity %> |
<%= link_to 'Back', family_affinities_path %>

app/views/original_views/family_affinities/index.html.erb
<h1>Listing family_affinities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Membid</th>
      <th>Relationship</th>
      <th>Other type value</th>
      <th>Connection name</th>
      <th>Connection membid</th>
      <th>Comment</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @family_affinities.each do |family_affinity| %>
      <tr>
        <td><%= family_affinity.name %></td>
        <td><%= family_affinity.membid %></td>
        <td><%= family_affinity.relationship %></td>
        <td><%= family_affinity.other_type_value %></td>
        <td><%= family_affinity.connection_name %></td>
        <td><%= family_affinity.connection_membid %></td>
        <td><%= family_affinity.comment %></td>
        <td><%= family_affinity.created_at %></td>
        <td><%= family_affinity.updated_at %></td>
        <td><%= link_to 'Show', family_affinity %></td>
        <td><%= link_to 'Edit', edit_family_affinity_path(family_affinity) %></td>
        <td><%= link_to 'Destroy', family_affinity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family affinity', new_family_affinity_path %>

app/views/original_views/family_affinities/new.html.erb
<h1>New family_affinity</h1>

<%= render 'form' %>

<%= link_to 'Back', family_affinities_path %>

app/views/original_views/family_affinities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @family_affinity.name %>
</p>

<p>
  <strong>Membid:</strong>
  <%= @family_affinity.membid %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @family_affinity.relationship %>
</p>

<p>
  <strong>Other type value:</strong>
  <%= @family_affinity.other_type_value %>
</p>

<p>
  <strong>Connection name:</strong>
  <%= @family_affinity.connection_name %>
</p>

<p>
  <strong>Connection membid:</strong>
  <%= @family_affinity.connection_membid %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @family_affinity.comment %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @family_affinity.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @family_affinity.updated_at %>
</p>

<%= link_to 'Edit', edit_family_affinity_path(@family_affinity) %> |
<%= link_to 'Back', family_affinities_path %>