config/routes.rb
FamilyLinux::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "family_data/tree"
  get "family_data/details"
  resources :family_start_points

  resources :family_documents

  resources :family_data

  resources :family_aliases

  resources :family_affinities

  

end

app/models/family_start_point.rb
class FamilyStartPoint < ActiveRecord::Base
end

app/controllers/family_start_points_controller.rb
class FamilyStartPointsController < ApplicationController
  # GET /family_start_points
  # GET /family_start_points.xml
  def index
    @table_count = FamilyStartPoint.count
    prep_nav_values( params )
    @family_start_points = FamilyStartPoint.find( :all, 
        :order => 'family_descrip', 
        :offset => @offset, :limit => @max_rows )
    @name_for_membid = Hash.new
    @family_start_points.each { | family_start_point | 
        @name_for_membid[ family_start_point.membid ] = 
        FamilyDatum.find_by_membid( family_start_point.membid ).name if
        family_start_point.membid }
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @family_start_points }
    end
  end

  # GET /family_start_points/1
  # GET /family_start_points/1.xml
  def show
    @family_start_point = FamilyStartPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @family_start_point }
    end
  end

  # GET /family_start_points/new
  # GET /family_start_points/new.xml
  def new
    @family_start_point = FamilyStartPoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @family_start_point }
    end
  end

  # GET /family_start_points/1/edit
  def edit
    @family_start_point = FamilyStartPoint.find(params[:id])
  end

  # POST /family_start_points
  # POST /family_start_points.xml
  def create
    @family_start_point = FamilyStartPoint.new(params[:family_start_point])

    respond_to do |format|
      if @family_start_point.save
        flash[:notice] = 'FamilyStartPoint was successfully created.'
        format.html { redirect_to(@family_start_point) }
        format.xml  { render :xml => @family_start_point, :status => :created, :location => @family_start_point }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @family_start_point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /family_start_points/1
  # PUT /family_start_points/1.xml
  def update
    @family_start_point = FamilyStartPoint.find(params[:id])

    respond_to do |format|
      if @family_start_point.update_attributes(params[:family_start_point])
        flash[:notice] = 'FamilyStartPoint was successfully updated.'
        format.html { redirect_to(@family_start_point) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @family_start_point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /family_start_points/1
  # DELETE /family_start_points/1.xml
  def destroy
    @family_start_point = FamilyStartPoint.find(params[:id])
    @family_start_point.destroy

    respond_to do |format|
      format.html { redirect_to(family_start_points_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/originals/family_start_points_controller.rb
class FamilyStartPointsController < ApplicationController
  before_action :set_family_start_point, only: [:show, :edit, :update, :destroy]

  # GET /family_start_points
  # GET /family_start_points.json
  def index
    @family_start_points = FamilyStartPoint.all
  end

  # GET /family_start_points/1
  # GET /family_start_points/1.json
  def show
  end

  # GET /family_start_points/new
  def new
    @family_start_point = FamilyStartPoint.new
  end

  # GET /family_start_points/1/edit
  def edit
  end

  # POST /family_start_points
  # POST /family_start_points.json
  def create
    @family_start_point = FamilyStartPoint.new(family_start_point_params)

    respond_to do |format|
      if @family_start_point.save
        format.html { redirect_to @family_start_point, notice: 'Family start point was successfully created.' }
        format.json { render action: 'show', status: :created, location: @family_start_point }
      else
        format.html { render action: 'new' }
        format.json { render json: @family_start_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /family_start_points/1
  # PATCH/PUT /family_start_points/1.json
  def update
    respond_to do |format|
      if @family_start_point.update(family_start_point_params)
        format.html { redirect_to @family_start_point, notice: 'Family start point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @family_start_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /family_start_points/1
  # DELETE /family_start_points/1.json
  def destroy
    @family_start_point.destroy
    respond_to do |format|
      format.html { redirect_to family_start_points_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_start_point
      @family_start_point = FamilyStartPoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_start_point_params
      params.require(:family_start_point).permit(:family_descrip, :membid, :comment, :created_at, :updated_at)
    end
end

app/helpers/family_start_points_helper.rb
module FamilyStartPointsHelper
end

app/views/family_start_points/edit.html.erb
<h1>Editing family_start_point</h1>

<% form_for(@family_start_point) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :family_descrip %><br />
    <%= f.text_field :family_descrip %>
  </p>
  <p>
    <%= f.label :membid %><br />
    <%= f.text_field :membid %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @family_start_point %> |
<%= link_to 'Back', family_start_points_path %>

app/views/family_start_points/index.html.erb
<p><large><b>Listing start points for family tree</b></large> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;    <%= link_to 'New start point for family tree', new_family_start_point_path %></p>
    <%= render( :partial => "shared/nav_line", :object => "index"  ) %>
<h1>Listing family_start_points</h1>

<table>
  <tr>
    <th> Description <br /> of starting point </th>
    <th> &nbsp; </th>
    <th> &nbsp; </th>
    <th> &nbsp; </th>
    <th> &nbsp; </th>
  </tr>
<% for family_start_point in @family_start_points %>
  <% delete_msg = "Are you sure you want to delete start point '" + 
        family_start_point.family_descrip + "'" +
        ( @name_for_membid && @name_for_membid[ family_start_point.membid ] ?
           " beginning with '" + 
           @name_for_membid[ family_start_point.membid ] + "'" : "" ) + "?" %>
  <tr>
    <td>
      <%= link_to family_start_point.family_descrip, { :controller => 'family_data', 
          :action => 'tree_show', :membid => family_start_point.membid }  %>
    </td>
    <td> &nbsp; </td>
    <td><%= link_to "View,", family_start_point %>
    <%= link_to 'Edit, or', edit_family_start_point_path(family_start_point) %>
    <%= link_to 'Destroy', family_start_point, :confirm => delete_msg, :method => :delete %>
 record of starting point</td>
  </tr>
  <% if family_start_point.comment && ( family_start_point.comment.length > 0 ) %>
    <tr><td colspan='5'>Comment: <%=h family_start_point.comment %></td></tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New start point for family tree', new_family_start_point_path %>

app/views/family_start_points/new.html.erb
<h1>New family_start_point</h1>

<% form_for(@family_start_point) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :family_descrip %><br />
    <%= f.text_field :family_descrip, :tabindex => 2 %>
  </p>
  <p>
    <%= f.label :membid %><br />
    <%= f.text_field :membid, :tabindex => 2 %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :tabindex => 3 %>
  </p>
  <p>
    <%= f.submit "Create", :tabindex => 4 %>
  </p>
<% end %>

<%= link_to 'Back', family_start_points_path %>

app/views/family_start_points/show.html.erb
<p>
  <b>Family descrip:</b>
  <%=h @family_start_point.family_descrip %>
</p>

<p>
  <b>Membid:</b>
  <%=h @family_start_point.membid %>
</p>

<p>
  <b>Comment:</b>
  <%=h @family_start_point.comment %>
</p>


<%= link_to 'Edit', edit_family_start_point_path(@family_start_point) %> |
<%= link_to 'Back', family_start_points_path %>